spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:dbtest
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    embedded-database-connection: h2
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://dpg-cr9hsqbv2p9s73b8bfkg-a.frankfurt-postgres.render.com/dlobaldb
    username: dlobaldb_user
    password: Qo7ue1ZlecvL1YjYANMYDyOQgqXNIag8
  jpa:
    generate-ddl: true
    show-sql: true
server:
  port: 9000
---



